### ISSUE TITLE
Killing a super mutant too fast causes the game to become unresponsive.

### ISSUE THREAD

**Issue by NotMergot** [ARF-SS13/coyote-bayou#2118]
---- Testmerges: ----
Round ID: 2005
BYOND Version: 514.1589
Server revision compiled on: 2023-04-30T04:01:20+00:00
Master commit: [34b3977c6413222a8459e8fa427680028ebfd007](https://github.com/ARF-SS13/coyote-bayou/commit/34b3977c6413222a8459e8fa427680028ebfd007)
TGS version: 5.2.4
DMAPI version: 5.6.0

Current Informational Settings:
Protect Authority Roles From Traitor: 0
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1

---- Reproduction: ----

Killing a supermutant (sledgehammer) crashed the game. Weapons used was a plasma cutter and fists (assume they had fists of the north star bc of punch speed), entity died and game crashed on the same frame.

---- Screenshots: ----
(https://www.youtube.com/watch?v=cd27phmQUeY) <--- Short video of the crash, had shadowplay on

---- Additional context: ----

Was at the bottom of a medical ruin, unsure what else to put.

**Comment by Tk420634** [comment]
Yeah, this is a known issue.  The problem is literally no one can recreate is consistently.  Sometimes it happens to some people with some mobs.  Sometimes it doesn't.  If you ever run into more info feel free to toss it in here, we're pretty sure it may be something similar to how players get rotated sometimes when taking damage.

**Comment by Tk420634** [comment]
Sorted out, combat logs are a bitch.
