### ISSUE TITLE
Moodlet Sound Repeating

### ISSUE THREAD

**Issue by intense-skies** [ARF-SS13/coyote-bayou#2979]
The mood buff sound + text plays repeatedly if something such as alcohol is consumed. (Occured with drinking vodka. No alcohol related perks were on the character.)

Also, it would be quite nice if there was a preference toggle for the sound/text of it. I personally do not desire the notifications and think a few others may also prefer to opt out if possible.
![Capture](https://github.com/ARF-SS13/coyote-bayou/assets/78576135/7cad65b4-4693-4b06-96e9-e4fb6e3d58b1)

**Comment by Tk420634** [comment]
Fixed in post!  A sound toggle should come later, but right now half the reason they exist is to find quirks doing exactly this.  Remember, they were triggering like that BEFORE the sound was added to them.  We will hunt them down!

I'll leave it open so we can remember the preference toggle tho, if its not in after a week or two slap me with a buick.

**Comment by intense-skies** [comment]
@Tk420634 
This is your approximately 2 week ping with a prayer requesting a toggle somewhere for the moodlet changes. 🙏

**Comment by Tk420634** [comment]
Yeah, not gonna happen.
